public class customizerdata {
    public String version;
	public String customtype;
	public String ramsideloc;
	public String productkey;
	public String ramvertloc;
	public String ramorientation;
	public String custpreview;
	public String warpedpreview;
	public String laserimage;
	public Prepared prepared;

	public class Prepared {
		public String itemid;
		public String itemkeyid;
		public String itembasekey;
		public Boolean premium;
	}
  

}