@isTest 
public with sharing class TestDataGenerator_Test {
  
  static testMethod void TestDataGeneratorUnitTest() {
        TestDataGenerator data = new TestDataGenerator();
       // data.initAllTestData();        
        //System.assertEquals(data.accountNum, data.getAccounts(true).size(),'Account size not equal to accountNum');
        //System.assertNotEquals(null,data.getOpportunityLineItems(true)[0].Id);                           
    }
    

}