/*
* -----------------------------------------------------------
* Apex Class Name: Test_CaseUtil
* -----------------------------------------------------------
* Description: This class contains test methods for all methods
* within the CaseUtil class.
* -----------------------------------------------------------
* Created by: Jeff Rogers, Alternative Technology Solutions.
* Created on: 2013-10-11
* Last Modified by: 
* Last Date Modified: 
* Modification Log:
* 1 - 
*/

@isTest
private class Test_CaseUtil{
    
    static testMethod void testCaseTrigger() {
        //test data with insert/update
       // acCore__FOB__c fob = TestDataUtility.newFOB('Origin', 'OR');
       // acCore__PaymentTerms__c pt = TestDataUtility.newPaymentTerms('Credit Card', 'CC');
       // Account a = TestDataUtility.newAccount('Test Account', 'Customer', null);
      //  Contact con = TestDataUtility.newContact(a, 'Test Contact');
       // Case c = TestDataUtility.newCase(a, con);
       // update c;
        
    }
        
}