public Class wDealerCase{
        public @AuraEnabled string CaseOwnerId;
        public @AuraEnabled string CaseOwnerName;       
        public @AuraEnabled string AccountId;
        public @AuraEnabled string AccountName;        
        public @AuraEnabled string Status;      
        public @AuraEnabled string ContactId;
        public @AuraEnabled string ContactName;     
        public @AuraEnabled string Priority;         
        public @AuraEnabled boolean TradingPostVisible;
        public @AuraEnabled string CaseCurrency;        
        public @AuraEnabled string Subject; 
        public @AuraEnabled string Description; 
        public @AuraEnabled string CaseOrigin; 
        public case caseObj;
        public wDealerCase(){}
    }